<?php
$functions = array(
    'local_student_core_email_verification' => array(
        'classname' => 'local_student_core_external',
        'methodname' => 'email_verification',
        'classpath' => 'local/student_core/externallib.php',
        'description' => 'Check if email is already in use for the caregiver',
        'type' => 'write',
        "ajax" => true,
        'capabilities' => 'moodle/user:create',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    
    'local_student_core_getcourses_bytoken' => array(
        'classname' => 'local_student_core_external',
        'methodname' => 'getcourses_bytoken',
        'classpath' => 'local/student_core/externallib.php',
        'description' => 'Return courses and activities by user logged',
        'type' => 'write',
        "ajax" => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_user_data_caregiver' => array(
        'classname' => 'local_student_core_external',
        'methodname' => 'user_data_caregiver',
        'classpath' => 'local/student_core/externallib.php',
        'description' => 'Return Info related users caregiver',
        'type' => 'write',
        "ajax" => true,
        'capabilities' => 'moodle/user:create',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_get_profile_image' => array(
        'classname' => 'local_student_core_external',
        'methodname' => 'get_profile_image',
        'classpath' => 'local/student_core/externallib.php',
        'description' => 'Return url profile image by user',
        'type' => 'write',
        "ajax" => true,
        'capabilities' => 'moodle/user:create',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_update_profile_image' => array(
        'classname' => 'local_student_core_external',
        'methodname' => 'update_profile_image',
        'classpath' => 'local/student_core/externallib.php',
        'description' => 'Method updated profile image caregiver',
        'type' => 'write',
        "ajax" => true,
        'capabilities' => 'moodle/user:create',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_get_messages' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'get_user_message',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Get a Json list of userid messages',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_get_caregiver' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'get_caregiver',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Get a name caregiver student',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_get_payment_data' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'get_payment_data',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Get a data process payment',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_get_level_points' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'get_level_points',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Get a points xp and level by user in specific course',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_update_payment_data' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'update_payment_data',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Update payment status',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_change_password' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'change_password',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Change password by caregiver',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_get_theme_settings' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'get_theme_settings',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Get Theme settings',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_student_core_get_user_filed' => array(
        'classname'   => 'local_student_core_external',
        'methodname'  => 'get_user_filed',
        'classpath'   => 'local/student_core/externallib.php',
        'description' => 'Get Theme settings',
        'type'        => 'read',
        "ajax"        => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
);
